/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as paymentPortalSol from "./PaymentPortal.sol";
export type { paymentPortalSol };
export type { MockERC20 } from "./MockERC20";
export type { MockIDR } from "./MockIDR";
export type { MockMYR } from "./MockMYR";
export type { MockPHP } from "./MockPHP";
export type { MockRouter } from "./MockRouter";
export type { MockSGD } from "./MockSGD";
export type { MockTHB } from "./MockTHB";
export type { MockVND } from "./MockVND";
